<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn</name>
   <tag></tag>
   <elementGuidId>c40a6222-7620-4f14-979f-d651f324b9f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//button[(text()='${label}')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[(text()='${label}')])[1]</value>
      <webElementGuid>cdb367e9-b549-4bbb-b604-01f4da28c8b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
