<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>b30b0ad2-7f80-4d7c-8e0e-707e6759133e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>svg[data-testid='${label}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>svg[data-testid='${label}']</value>
      <webElementGuid>044dcaeb-e4f9-48e8-bb91-cecc82ebc6b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
